config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts do
       resources :comments
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :post, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
 has_many :comments, dependent: :destroy
 validates :title, presence: true
 validates :body, presence: true
 belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.email = current_user.email
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js # added @10/24/2015
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.email = current_user.email
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

   # def authenticate
      #authenticate_or_request_with_http_basic do |name , password|
      #name == "admin" && password =="secret"
    #end 
    #end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<p> 
		<strong> Posted <%=  time_ago_in_words(comment.created_at) %>  </strong> <br/>
		<%= h(comment.body) %>
		  <%  if user_signed_in? %>
		<% if current_user.email == comment.email %>
		<%= link_to 'Edit Comment' , edit_comment_path(comment) %>
		<% end %>
		<% end %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', posts_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="moon" class="moon-orbit">
   <div class="moon" ></div>
</div>


</div>
<style>
@import url(https://fonts.googleapis.com/css?family=Orbitron:400,700);

html, body {height: 100%; }

*,
*:before,
*:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box; }

body {
	height:100%; 
	margin: 0; 
	padding: 0;
	font-size: 100%;
	font-weight: 400;
	font-style: normal;
	line-height: 1.3;
	width:100%;
	color:#fff;
	font-family: 'Orbitron', sans-serif;
	background-image:url(http://solarscroller.rhettforbes.com/img/stars.jpg);
	background-repeat: repeat;
	background-color:#000;
	overflow:scroll;
  -webkit-animation: sky 82s linear infinite;
  -moz-animation: sky 82s linear infinite;
	-ms-animation: sky 82s linear infinite;
	-o-animation: sky 82s linear infinite;
	animation: sky 82s linear infinite;}
	

	

@keyframes oz{
	0% {z-index: 12;}
	25% {z-index: 12;}
	50% {z-index: 12;}
	100% {z-index: 5;}
}
@-webkit-keyframes oz{
	0% {z-index: 5;}
	25% {z-index: 26;}
	50% {z-index: 5;}
	100% {z-index: 5;}
}
@keyframes sky {
 50% {background-position: 600px 0px;}
 100% {background-position: 1200px 0px;}
}
@-moz-keyframes sky {
 50% {background-position: 600px 0px;}
 100% {background-position: 1200px 0px;}
}
@-webkit-keyframes sky {
 50% {background-position: 600px 0px;}
 100% {background-position: 1200px 0px;}
}

h1, h2, h3, h4, h5, h6 {
	font-family: 'Orbitron', sans-serif; 
	font-weight:700;
	margin:0; 
	padding:0;
	line-height:1.3;}
	h6 { font-weight:400;}

.logo {
	width:100%;
	position:absolute;
  text-align: center;
	top:0;
	padding:1.5rem;}
  .logo h1 {letter-spacing: 0.1em;}

.content { 
  width:100%; 
  max-width:575px; 
  position:absolute; 
  bottom:0;
  text-align:left; 
  padding:1rem; 
  opacity:0.3; 
  transition: opacity 0.5s ease;}
  .content:hover { opacity:1;}

p {
  font-size:14px; 
  line-height:1.5; 
  font-family:Gotham, "Helvetica Neue", Helvetica, Arial, sans-serif; 
  color:rgba(255,255,255,0.75)}

a  { 
  text-decoration:none; 
  color:#f90;
  transition: color 0.5s ease;}
  a:hover  { color:#fff;}



#email_id {
	color:#f90;
}

</style>





	<div id= "user_nav" align="right" >
	 <% if user_signed_in? %>
		signed in as <h4 id ="email_id"> <%= current_user.email %>. </h4>  Not you ?
	    <%= link_to "sign out", destroy_user_session_path, :method => :delete %>
	<% else %>
		<%= link_to "sign up" , new_user_registration_path  %> or <%= link_to "sign in", new_user_session_path %>
	<% end %>
	</div>
<% flash.each do |name, msg| %>;
  <%= content_tag :div, msg, :id => "flash_#{name}" %>;
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<style>
#editfor {
	background-color:rgba(72,72,72,0.4);
	padding-left:35px;
	padding-right:35px;
	padding-top:35px;
	padding-bottom:50px;
	width: 450px;
	float: left;
	left: 50%;
	position: absolute;
  margin-top:30px;
	margin-left: -260px;
  -moz-border-radius: 7px;
  -webkit-border-radius: 7px;
}
</style>
<h1 align="center">Editing Post</h1>

<div id="editfor">
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<style>
#defaultposts {
  background-color:rgba(72,72,72,0.4);
  padding-left:35px;
  padding-right:35px;
  padding-top:35px;
  padding-bottom:50px;
  width: 450px;
  float: left;
  left: 50%;
  position: absolute;
  margin-top:30px;
  margin-left: -260px;
  -moz-border-radius: 7px;
  -webkit-border-radius: 7px;
}
</style>



<p id="notice"><%= notice %></p>

<h1 align="center">Listing Posts</h1>
<div id="defaultposts">
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        
        <td><%= link_to 'Show', post %></td>
        <%  if user_signed_in? %>
         <% if current_user.email == post.email %> 

        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end  %>
        <% end  %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<style>
#new_post {
	background-color:rgba(72,72,72,0.4);
	padding-left:35px;
	padding-right:35px;
	padding-top:35px;
	padding-bottom:50px;
	width: 450px;
	float: left;
	left: 50%;
	position: absolute;
  margin-top:30px;
	margin-left: -260px;
  -moz-border-radius: 7px;
  -webkit-border-radius: 7px;
}
</style>
<h1 >New Post</h1>

<%= link_to 'Back', posts_path %>

<%= render 'form' %>

app/views/posts/show.html.erb
<style>
#form-div {
	background-color:rgba(72,72,72,0.4);
	padding-left:35px;
	padding-right:35px;
	padding-top:35px;
	padding-bottom:50px;
	width: 450px;
	float: left;
	left: 50%;
	position: absolute;
  margin-top:30px;
	margin-left: -260px;
  -moz-border-radius: 7px;
  -webkit-border-radius: 7px;
}
</style>

<div id="form-div"  >
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<H2> Comments </H2>
<div id = "comments"> 
	<% @post.comments.each do |comment| %>
	<%= render :partial => @post.comments.reverse %>
<% end %>
</div>

<% if user_signed_in? %>
<% if current_user.email == @post.email %>
<%= form_for([@post, Comment.new] , remote: true ) do |f| %>
 <p> <%= f.label :body, "New Comment" %> <br/>
 <%= f.text_area :body %>
 </p>
 <p> <%= f.submit "Add Comment" %></p>
 <% end %>  

<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<% end %>
<%= link_to 'Back', posts_path %>
</div>